In [1]:
import Dynasplit as ds
import MDAnalysis as mda
import numpy as np

/opt/anaconda3/envs/Fresh/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


# Load an example Universe

In [2]:
u =mda.Universe('./test_traj/290k_end.data','./test_traj/sampled_100_frames.dcd')

/opt/anaconda3/envs/Fresh/lib/python3.12/site-packages/MDAnalysis/coordinates/DCD.py:165: DeprecationWarning: DCDReader currently makes independent timesteps by copying self.ts while other readers update self.ts inplace. This behavior will be changed in 3.0 to be the same as other readers. Read more at https://github.com/MDAnalysis/mdanalysis/issues/3889 to learn if this change in behavior might affect you.
  warnings.warn("DCDReader currently makes independent timesteps"


## Create an instance of the Dynnasplit class with the universe

In [3]:
splitter = ds.Dynasplit(u)

## The main feature of the class is decompose which produces an independent rotational and translational trajectory.

It can be called with .decompose(), if the indices and masses information is stored in the universe then no parameters are required, but specific indices and masses can be input. Currently only trajectories of the same molecules are supported.

In [7]:
u.trajectory[0].dimensions[0:3]

array([47.735985, 47.735985, 47.735985], dtype=float32)

In [9]:
 3.7728662 / 47.7

0.07909572746331237

In [4]:
splitter.decompose()


Centering molecules: 100it [00:00, 883.84it/s]

[[43.66784066 18.64097125 39.26793307]
 [13.1421807  44.77947404 24.96098146]
 [11.07671274  3.7728662  17.29625252]
 ...
 [29.68450551 22.35240043  2.83917368]
 [45.73904654 25.94280321 20.41146601]
 [28.21995958 43.34467911 12.64556375]]
[[42.57418909 18.62942536 37.96813415]
 [10.96047188 46.19078505 27.06514327]
 [13.276468    7.36962096 18.39558882]
 ...
 [33.9609993  25.06252417  5.33626623]
 [45.8922621  26.69280619 22.17789404]
 [23.49864616 42.56118699 13.71115311]]
[[ 0.52461832 19.43275853 38.96207318]
 [ 9.04000228  3.59262107 29.10004825]
 [ 8.81965512  2.83326198 18.28664705]
 ...
 [35.060528   27.15989261  3.38485213]
 [45.61415971 28.09082856 22.91821592]
 [17.60372014 38.02889201 18.32839801]]
[[47.32710685 15.04427549 39.93669772]
 [10.13005999 10.9247375  28.07725728]
 [11.15921613  2.72899764 17.41317393]
 ...
 [39.45327445 26.73581988  4.39117353]
 [44.76405564 24.64504784 21.55390528]
 [17.86249613 30.36440316 23.3260499 ]]
[[12.31983166 12.92725228 38.35246057]
 

Alternatively indices and masses can be specified as numpy arrays, both indices and masses should be shape (n_molecules, n_atoms_per_molecule). 

In [5]:
indices = np.arange(0,8748,1).reshape(-1,12)
masses = np.tile(np.array([12,12,12,12,12,12,1,1,1,1,1,1]),(729,1))
splitter.decompose(indices=indices,masses=masses)

Centering molecules: 0it [00:00, ?it/s]

[[43.66784513 18.64098749 39.26792048]
 [13.14218854 44.77945969 24.96097764]
 [11.07669139  3.77285359 17.29624633]
 ...
 [29.68452027 22.35241845  2.83918874]
 [45.7390964  25.94276439 20.41148013]
 [28.21998186 43.34466039 12.64552657]]
[[42.5741874  18.62942319 37.968125  ]
 [10.96046563 46.19077517 27.06514689]
 [13.27647952  7.36963421 18.39558015]
 ...
 [33.96099035 25.06248314  5.33629491]
 [45.89228239 26.69281056 22.17789699]
 [23.49864347 42.56119539 13.71115569]]
[[ 0.5245884  19.43274339 38.9620434 ]
 [ 9.04000064  3.59264104 29.1000686 ]
 [ 8.81966043  2.83324303 18.28664535]
 ...
 [35.06053523 27.15988161  3.38484793]
 [45.61417598 28.09083828 22.91820762]
 [17.60373594 38.02888029 18.32841863]]
[[47.32714498 15.04426786 39.93670495]
 [10.13004732 10.92470696 28.07729548]
 [11.1592064   2.72898617 17.41319024]
 ...
 [39.45326569 26.73583698  4.39114942]
 [44.76405239 24.64505291 21.55390203]
 [17.86249201 30.36443421 23.32605196]]
[[12.31981521 12.92725309 38.352463  ]
 

Centering molecules: 100it [00:00, 651.08it/s]

[[24.2713061   3.78999652 43.61992683]
 [16.90352574 25.42763396  4.08317269]
 [ 4.44190079 44.19913     2.495153  ]
 ...
 [ 6.35525406 21.33316436 13.5391001 ]
 [ 0.80243579 23.39038053  0.06099365]
 [46.40451643 25.41049547 23.22043472]]
[[20.93171573  6.23420447 42.6673996 ]
 [14.32822461 27.85827672  5.71901799]
 [10.26182902 46.92754874  4.73079871]
 ...
 [ 1.38540228 27.09884358 11.84033201]
 [ 3.51782885 26.41639098  1.15853815]
 [43.97908543 23.48080032 20.22757415]]
[[23.13234073  9.89696699 36.7200412 ]
 [20.30399245 20.16610519 15.78195524]
 [ 6.61546295 36.76499173 20.2732841 ]
 ...
 [ 6.60395004 22.0439762  23.23251774]
 [46.81528286 10.20823567 11.60353949]
 [ 2.38100673 23.75878766 18.68513964]]
[[13.64643583  5.690628   44.52890041]
 [20.42195206 20.51559681 18.8265736 ]
 [ 5.43514654 38.2561069  13.01521194]
 ...
 [ 3.05543225 27.17201505 21.11857685]
 [ 6.73515572 12.26022296 20.68823111]
 [ 0.16839688 35.80248007 23.42070862]]
[[16.65675062  6.17004749 43.61948095]
 

Alternatively MDAnalaysis can be used in which case only the atom types need to specified, in which case bond information is required

In [6]:
splitter.decompose(slower=True,atom_types='type 1 2 3 4 5 6 7 8 9 10 11 12')


Centering molecules: 0it [00:00, ?it/s]

[[-4.0681434 18.640972  -8.468051 ]
 [13.14218   -2.9565103 24.960981 ]
 [11.076713   3.7728662 17.296253 ]
 ...
 [29.684505  22.3524     2.8391736]
 [-1.9969386 25.942802  20.411467 ]
 [28.21996   -4.3913054 12.645564 ]]
[[ -5.161796   18.629425   -9.767851 ]
 [ 10.960472   -1.5452002  27.065144 ]
 [ 13.276468    7.3696213  18.395588 ]
 ...
 [-13.774985   25.062525    5.3362665]
 [ -1.8437229  26.692806   22.177895 ]
 [ 23.498646   -5.1747985  13.711153 ]]


Centering molecules: 3it [00:00, 22.71it/s]

[[  0.52461827  19.432758    -8.773911  ]
 [  9.040002     3.592621    29.100048  ]
 [  8.819655     2.833262    18.286648  ]
 ...
 [-12.675456    27.159893     3.3848522 ]
 [ -2.1218247   28.090828    22.918215  ]
 [ 17.60372     -9.707092    18.328398  ]]
[[-0.4088781 15.044275  -7.799287 ]
 [10.13006   10.924738  28.077257 ]
 [11.159216   2.7289977 17.413174 ]
 ...
 [-8.282709  26.735819   4.3911734]
 [-2.9719293 24.645048  21.553905 ]
 [17.862495  30.364403  23.32605  ]]
[[ 12.319832    12.927253    -9.383525  ]
 [ 23.35551      0.40565312  26.902515  ]
 [ 15.278925    -5.2054186   11.3895645 ]
 ...
 [-10.270613    30.665699     8.01121   ]
 [  3.2402105  -11.236691    18.722746  ]
 [ 19.91166     24.235       28.557001  ]]


Centering molecules: 6it [00:00, 23.60it/s]

[[ 14.004039    15.292209   -11.879305  ]
 [ 26.170483    -0.77657366  29.734955  ]
 [ 13.044506    -6.971246    11.478374  ]
 ...
 [ -8.516286    27.143646    -0.6715685 ]
 [ -0.908202    -7.974311    24.06701   ]
 [ 22.349716    21.256292    27.604694  ]]
[[ 12.604595   10.158287  -13.440649 ]
 [ 25.05392    -1.101444   30.946259 ]
 [ 12.6197    -12.74719    12.6197405]
 ...
 [ -3.6995296  25.4509      3.4586203]
 [ -4.0349984 -11.382049   25.090347 ]
 [ 23.76552    18.184114   28.444584 ]]
[[  8.974256    6.675225  -15.80468  ]
 [ 23.090508    1.9079889  29.938492 ]
 [  7.439805  -11.852222    5.928904 ]
 ...
 [ -6.2847357  24.253008    1.006503 ]
 [-11.847772   -8.407242   21.9965   ]
 [ 25.503643   15.733916   30.76612  ]]


Centering molecules: 9it [00:00, 24.23it/s]

[[ 11.530301    1.2981796  29.751905 ]
 [ 24.820492    2.4921482  31.010477 ]
 [  7.136566  -11.546988    1.8342094]
 ...
 [ -7.1115894  25.42191     1.3205135]
 [ -8.478623   -8.064407   22.305944 ]
 [ 24.825325   12.99685    31.95912  ]]
[[  9.506257    1.0042355 -16.038382 ]
 [ 20.588846   -0.9465908 -15.019613 ]
 [  3.6273918 -12.153988    3.7818215]
 ...
 [-10.625189   22.56895    -2.578655 ]
 [ -6.876064  -14.018679   21.396053 ]
 [ 21.63394    12.21524   -15.035428 ]]
[[  8.916283   6.182545 -12.097116]
 [ 27.699553   4.64078   25.348295]
 [ 23.748001  -9.321335  11.460361]
 ...
 [ -5.446705  22.073778  -9.561216]
 [-10.697035  -5.480137  16.367624]
 [ 19.014074  14.199194  19.08273 ]]


Centering molecules: 12it [00:00, 24.46it/s]

[[  1.4750546   9.8397875  29.835468 ]
 [ -8.996107    6.733855   24.030111 ]
 [ -9.822123   31.347036   19.931585 ]
 ...
 [-14.458692  -15.262042   -1.3155959]
 [ 29.633324   -4.6529984  13.262552 ]
 [-11.063697   22.470844   12.4465475]]
[[ 11.134782   10.272031   23.518898 ]
 [ -7.8323054   6.0001903  23.225372 ]
 [-15.966724   24.612356   29.1435   ]
 ...
 [-15.174433  -11.470097    1.7922132]
 [ 26.648083   27.462278    3.2557251]
 [ -7.7251673  -7.2233753  21.522058 ]]
[[ 14.959337   13.417791   24.10739  ]
 [ -3.1249712   5.2582073  23.015617 ]
 [-14.800063   22.909277   22.208624 ]
 ...
 [ 27.262484   30.17513     0.7677133]
 [ 25.721352   25.754847   -1.3772964]
 [ -5.656243   -8.297289   20.147816 ]]


Centering molecules: 15it [00:00, 24.40it/s]

[[ 11.729706    13.566845    23.136473  ]
 [ -4.3121443    5.6964903   23.849249  ]
 [-13.511363    23.176601    25.328617  ]
 ...
 [ 28.390945    29.788912    -0.97933346]
 [ 27.439983    24.984413    -1.4396267 ]
 [ -5.9690633   -7.7422214   22.149406  ]]
[[ 16.68248     21.893705    22.333553  ]
 [-14.240959     0.2717974   29.7957    ]
 [ 29.549955    21.552725    19.501827  ]
 ...
 [ 30.782372   -10.55736      0.43153876]
 [ 23.135826    13.795753    -1.387218  ]
 [ -3.1694338    3.7595723   23.367474  ]]


Centering molecules: 18it [00:00, 24.82it/s]

[[ 12.0813055   22.46235     19.77946   ]
 [ 31.105766    -0.73361766  28.049248  ]
 [ 29.7368      17.64385     20.635015  ]
 ...
 [-16.675486    -8.345013     3.2888458 ]
 [ 21.46729     13.146474    -5.9151506 ]
 [ -5.239952     6.9334493   23.178764  ]]
[[ 15.2571     17.883255   20.84362  ]
 [ 22.37317    -7.445096   22.432589 ]
 [-13.835805   17.029482   25.11809  ]
 ...
 [-17.380854  -10.532096    4.477442 ]
 [ 17.32627    15.496399  -12.162067 ]
 [ -3.8027294   8.211077   26.109161 ]]
[[ 16.528694   22.786407   23.791374 ]
 [ 18.954273   31.090473   29.4771   ]
 [ 31.129982   21.860796   26.454475 ]
 ...
 [ 25.465221  -12.42517    -1.4369522]
 [ 17.972393   23.808859    2.9938278]
 [ -1.8901645   1.3495413 -15.35586  ]]
[[  9.439927   24.902376   26.40831  ]
 [ 27.13195   -14.084683  -15.970409 ]
 [ 21.79497    19.196726   25.70154  ]
 ...
 [ 29.036427   21.450277    4.6031966]
 [ 13.708559   20.712015    1.2775849]
 [-11.184407  -11.02275    31.314192 ]]


Centering molecules: 21it [00:00, 24.62it/s]

[[  3.7054725  15.197793   -6.3967   ]
 [ 24.111427   29.841644    1.5102326]
 [  8.849941   25.298525  -10.063344 ]
 ...
 [ 23.792131   28.411663   14.571771 ]
 [ 23.299702   14.272231    7.4957957]
 [ -9.303605  -14.11778    29.690763 ]]


Centering molecules: 24it [00:00, 24.74it/s]

[[11.798937  22.043644   4.379204 ]
 [27.870745  26.475822  11.199827 ]
 [10.07559   21.857534  -1.503877 ]
 ...
 [20.74888   26.954292  20.682695 ]
 [28.617428  12.8409395 19.183878 ]
 [28.208168  29.475746  27.022423 ]]
[[ 10.348659   20.46999    17.488981 ]
 [ 12.744558    4.92276    -8.653334 ]
 [ 16.414995   17.787891   -2.7884543]
 ...
 [  0.3420957  19.393549   -8.015141 ]
 [ -9.543146   32.06815     9.974133 ]
 [ -9.860114   22.519981  -10.651924 ]]
[[ 11.887491    27.426462    16.398952  ]
 [  5.4293175    4.6736593   -7.3596573 ]
 [ 17.889715    24.633509     0.51271915]
 ...
 [  1.0531231   17.915995   -11.186141  ]
 [ -7.2039156  -12.859833    13.346017  ]
 [ 26.342688    16.063486   -13.171171  ]]
[[  4.3866887  22.285929   29.128311 ]
 [  4.8950024  -6.066815   -4.2840886]
 [ 10.961653  -13.426213   -5.5700216]
 ...
 [ -3.3089683  13.561062   -4.818693 ]
 [ -9.490161   29.876871   12.007878 ]
 [ 19.096325   20.45148   -13.025882 ]]
[[ 24.00612    13.124058   25.650076 ]
 

Centering molecules: 30it [00:01, 25.11it/s]

[[ 21.370142    8.840047   18.985956 ]
 [ 10.49448    -2.0669286 -12.145421 ]
 [ 16.81947    -0.4077538 -14.166237 ]
 ...
 [  7.875833   16.449244    5.930097 ]
 [ 32.02969    -6.7790513   8.145599 ]
 [  1.8062043  27.03143    17.92926  ]]
[[ 23.796825   13.265911   18.630566 ]
 [  8.37545    -1.9396852 -12.150186 ]
 [ 17.72477     3.0639904 -13.57378  ]
 ...
 [ 10.154113   13.994592    3.8203092]
 [-12.800255   -6.668506    5.7518144]
 [  1.5330421  25.618975   17.142635 ]]
[[ 28.183113   12.222429  -15.501593 ]
 [  8.301869  -11.163416   26.983913 ]
 [ 25.049112    5.6000857 -12.150565 ]
 ...
 [  1.5036042  18.118431   12.638924 ]
 [  0.5261522   4.128577   17.050478 ]
 [ -6.021866   26.17418    10.380213 ]]
[[-16.441736   13.765636   30.310831 ]
 [  5.754201  -13.440233  -15.64824  ]
 [ 26.10752     4.169459  -11.397453 ]
 ...
 [  4.1993155  16.88671    13.551327 ]
 [  0.8604666   7.610899   14.244514 ]
 [ -8.03328    30.377317   10.742692 ]]
[[ 28.260565     9.472139   -11.336424  

Centering molecules: 36it [00:01, 24.60it/s]

[[ 28.896475     3.2024384   -8.358035  ]
 [  7.7059727  -11.651208   -10.492724  ]
 [ 18.37743     -9.705286    -9.516805  ]
 ...
 [  1.5768888   10.667241    10.883482  ]
 [  5.345287    13.223932     2.1001148 ]
 [ -0.88038826  24.326895    10.900661  ]]
[[ 31.538223     7.090772    -4.7412143 ]
 [  8.206289   -11.388011    -8.677224  ]
 [ 17.535957   -12.934616    -8.675627  ]
 ...
 [  2.0332093    3.1789963   11.79788   ]
 [  8.796262    13.980917     0.24937318]
 [ -2.507491    18.23323     13.783318  ]]
[[ 29.47846     6.979869   -5.6533027]
 [ 10.57482   -12.467888   -6.582217 ]
 [ 19.601368   -9.560247   -7.463476 ]
 ...
 [ 11.260909   11.004788   16.077877 ]
 [ -4.329719   19.315416    1.7943938]
 [ -2.7532828  25.213812   17.576952 ]]
[[30.135807    9.124389   -4.750169  ]
 [ 5.1505904  -9.10072    -5.8556137 ]
 [ 9.59695    -7.3943505  -2.6609201 ]
 ...
 [ 7.3724785  15.430068   15.792049  ]
 [ 0.23558328 17.052246    4.3503923 ]
 [ 2.5844984  26.62045    24.146484  ]]
[[ 2

Centering molecules: 42it [00:01, 24.90it/s]

[[27.62248     5.4578385  -7.755636  ]
 [13.399913   -8.143243   -4.3872514 ]
 [ 8.316241   -9.396788    0.05187267]
 ...
 [ 3.6965847  15.465362   19.122854  ]
 [-1.5566738  13.3441      3.0723233 ]
 [ 2.8374312  22.619656   18.213572  ]]
[[ 27.16035      2.7776709   -8.601393  ]
 [ 18.355343   -12.974275     0.16003452]
 [ 12.25473     -7.586403    -0.8867005 ]
 ...
 [  8.406842    13.516701    20.160248  ]
 [ -4.157377    16.149717    -9.293329  ]
 [ -0.7003599   22.952448    23.08071   ]]
[[30.79472    5.7463136 -3.658018 ]
 [14.424309  30.275213  -1.2951429]
 [ 9.851415  -3.39125   -4.8965173]
 ...
 [ 9.266785  21.563583  10.255751 ]
 [-0.8482702 23.115019  -0.9190298]
 [ 2.9027529 24.79617   27.438145 ]]
[[24.271317    3.7900186  -4.1160398 ]
 [16.903542   25.42765     4.0831566 ]
 [ 4.4418993  -3.5368652   2.495151  ]
 ...
 [ 6.355262   21.333172   13.539098  ]
 [ 0.8024339  23.39035     0.06098973]
 [-1.3314861  25.410511   23.22043   ]]
[[20.931732   6.23421   -5.0685854]
 [14

Centering molecules: 48it [00:01, 24.88it/s]

[[ 13.646422     5.6906176   -3.2070832 ]
 [ 20.421923    20.515593    18.82657   ]
 [  5.4351482   -9.4798355   13.01518   ]
 ...
 [  3.0554252   27.172003    21.118576  ]
 [  6.735146    12.260244    20.68821   ]
 [  0.16834676 -11.933547    23.420727  ]]
[[ 16.656763    6.1700416  -4.1165013]
 [ 17.881107   21.080093   17.94714  ]
 [  7.626207  -13.911471   11.63445  ]
 ...
 [ -1.0088735  25.418026   21.558771 ]
 [ 11.0662365  16.065834   21.168156 ]
 [  1.3846045 -13.614406   23.565037 ]]
[[ 16.13941     2.4377425  -4.240107 ]
 [ 16.645452   20.761974   14.540733 ]
 [ 12.188222  -10.106182   15.048734 ]
 ...
 [ -9.218134   27.862185   25.814398 ]
 [ 10.983841   11.876464   17.110407 ]
 [  1.204355  -13.448142   26.581242 ]]
[[ 16.357634   -2.6844313  -4.812726 ]
 [ 17.368032   21.603624   18.437847 ]
 [ 13.9002695  -7.928905   16.245682 ]
 ...
 [-10.74383    29.771832   25.094961 ]
 [ 12.243756   12.524458   17.908806 ]
 [  1.6894373 -12.1200485  25.899284 ]]
[[ 20.149805  -13.0811

Centering molecules: 54it [00:02, 24.95it/s]

[[ 11.930019   24.444727   -7.559095 ]
 [ 10.90117    24.320122  -12.877138 ]
 [ 13.40227     1.1240917  10.359394 ]
 ...
 [ -9.017578   27.975002   18.724325 ]
 [ 19.762312    9.657796    4.5270357]
 [ 12.609171   22.865828   26.40604  ]]
[[  7.573698   31.178076  -11.687793 ]
 [ 23.58135    -7.0592957 -14.470977 ]
 [ 15.946099   11.973715   14.603507 ]
 ...
 [ 31.952013    6.1044474   7.571216 ]
 [ 18.556591   -1.1150848  -8.339015 ]
 [ -1.6179057   1.4187928  -3.9190788]]
[[  9.632989  -14.402922  -11.102189 ]
 [ 23.083447  -11.788284  -15.838027 ]
 [ 18.294693   18.564526   20.122551 ]
 ...
 [ 28.593082    5.008887   10.602804 ]
 [ 18.577326    4.0515065 -10.348792 ]
 [ -1.7709501   3.3039207   0.9456639]]
[[  7.6888003  -11.004724    -8.973121  ]
 [ 26.433077    26.320684    17.84647   ]
 [ 14.253087    28.21568     18.776077  ]
 ...
 [-14.300491     0.8013779    3.682284  ]
 [ 19.240295    -0.12869008   0.8304539 ]
 [  0.14767735   1.929821     7.203968  ]]
[[ 10.297013  -16.0119

Centering molecules: 60it [00:02, 24.72it/s]

[[  9.582222   26.407839  -10.482808 ]
 [ 16.221645   24.721695   19.40705  ]
 [  7.7237444  27.791897   16.699722 ]
 ...
 [ 18.347153   29.98978    -4.0703316]
 [ 23.702972   13.001027    2.3566394]
 [ 30.608416   -3.0994775  16.94085  ]]
[[  9.265373    24.983446   -10.816948  ]
 [ 21.24527     28.204826    22.065647  ]
 [  6.1783595   27.371096    17.58787   ]
 ...
 [ 15.533421    29.928629    -3.0675702 ]
 [ 23.678148    13.777469    -0.07019181]
 [ 29.632801    -4.352966    17.606035  ]]
[[ 14.280331    29.090616    -9.795019  ]
 [ 28.115143    23.67955     25.91867   ]
 [ 11.677047    32.493843    18.02763   ]
 ...
 [ 19.990044   -16.669456    -0.66384536]
 [ 11.610469    11.544496    -3.1622136 ]
 [ 31.083397    -7.5820293   20.630173  ]]
[[ 14.42369    29.05922   -10.688389 ]
 [ 29.3266     24.655994   24.637877 ]
 [ 12.129615  -14.127594   16.385876 ]
 ...
 [ 21.658665   24.469109    0.3223531]
 [ 13.873832   12.601417   -6.151918 ]
 [ 26.153904   -6.4937897  15.765709 ]]
[[ 1

Centering molecules: 66it [00:02, 24.82it/s]

[[ 12.035688   27.472044    2.6999097]
 [ 29.552198   22.503622   19.305157 ]
 [  7.3103437 -12.728826   15.647052 ]
 ...
 [ 18.655123  -12.712359   -4.235752 ]
 [ 11.49084     3.6487377  -8.28065  ]
 [ 21.657988   -9.538253   10.916303 ]]
[[ 12.261891   28.376478   -0.6212308]
 [ 24.80548    25.6254     19.913643 ]
 [  3.6481962  30.333147   18.731586 ]
 ...
 [ 20.561972  -11.011089   -4.648066 ]
 [  5.4494567   4.1209664 -11.432754 ]
 [ 24.030806   -3.8534055  14.311408 ]]
[[  9.530141   28.773874   -2.3760018]
 [ 22.969007   23.743845   16.448126 ]
 [  1.2055924  30.156713   19.673203 ]
 ...
 [ 25.403358  -13.902164   -3.5659778]
 [  8.77642     4.488367   -8.485145 ]
 [ 26.630512   -2.1350641  15.67033  ]]
[[ 13.465837   25.603018    0.5065622]
 [ 27.81519    25.13343    11.414137 ]
 [  6.5706863   6.9542804  25.880596 ]
 ...
 [ 20.693077  -13.805526    3.2311556]
 [ 12.383722   -1.6247209  -2.112712 ]
 [ 14.15815   -11.446924   23.489794 ]]
[[ 11.843273   14.374133    6.31881  ]
 

Centering molecules: 72it [00:02, 24.72it/s]

[[  6.3701377  16.228779    6.2115946]
 [-15.505689  -12.795527   22.886374 ]
 [ 16.033098    5.965058   27.901934 ]
 ...
 [ 24.458584   19.135252    2.809931 ]
 [  8.53985    11.005243    2.035105 ]
 [ 23.77218     8.025181   27.410252 ]]
[[ -2.1624231   19.336782    -5.10009   ]
 [ 28.423477   -14.236799   -15.611636  ]
 [ 17.78721     10.350347    29.62649   ]
 ...
 [ 14.091822    19.555994     6.913419  ]
 [ -1.5392804   15.268176    -2.0480263 ]
 [ 21.9827       0.93657714  20.57786   ]]
[[  7.909402   19.169523   -5.6973805]
 [ 32.008842   22.64134    -8.820795 ]
 [ 24.748665   12.992462   25.108555 ]
 ...
 [ 18.166008   19.37748     5.2845187]
 [ -0.7046764   7.612697   -5.8623123]
 [-13.52662     1.5631003  15.239149 ]]
[[11.200512  18.18801   -5.547382 ]
 [26.627884  22.384586  -9.967315 ]
 [24.360544  12.632525  23.422554 ]
 ...
 [17.9485    18.890871   5.0417614]
 [ 1.2359337  6.444363  -1.8453034]
 [-2.9399533  2.394611  11.123476 ]]
[[ 15.3096     26.547861  -12.043535 ]
 

Centering molecules: 78it [00:03, 24.94it/s]

[[ 16.847406    25.422243    -3.6829033 ]
 [-13.916452    -5.3628273   -6.671324  ]
 [ 29.682713    -4.425013    23.138325  ]
 ...
 [ 10.234201    21.002638    -4.713419  ]
 [ -3.3752277    6.6655807   -5.3338494 ]
 [-13.6274185   24.9769       0.07213018]]
[[ 13.125945   -10.524866   -11.868634  ]
 [  0.64893633   1.4295787   -2.1265388 ]
 [-16.478878    -3.48017     24.233988  ]
 ...
 [ 12.253628    16.027386    -4.70634   ]
 [  6.350754    19.237728    -7.617522  ]
 [-15.382676    25.761623     6.4282246 ]]
[[ 24.53908   -13.727448   30.002813 ]
 [  1.5095807  -3.2909899  -7.9950976]
 [-11.9723425  -1.6026895  20.298086 ]
 ...
 [ 12.020804   20.262423  -10.322141 ]
 [  7.102719   21.35737     1.611243 ]
 [ 23.458883   23.401737    8.351235 ]]
[[ 26.431822   -14.627951    30.243053  ]
 [  3.5674014   -0.90381515  -9.537225  ]
 [-13.501429     0.9711693   19.649944  ]
 ...
 [  9.697667    15.137913    -8.177671  ]
 [  5.2518992   19.406954     0.5891993 ]
 [ 24.267494    24.334904    

Centering molecules: 84it [00:03, 24.65it/s]

[[-12.629609     4.358965    27.575403  ]
 [  0.74430573  -4.352798    29.990618  ]
 [ -2.9881144   12.866749    17.334023  ]
 ...
 [ 22.35656      5.153051    23.883717  ]
 [ 21.617872     6.3814673  -11.058518  ]
 [-17.034714    23.791525    21.471954  ]]
[[-14.835007     2.2058914   26.531885  ]
 [ -0.77793723  -1.9289727  -12.598327  ]
 [ -2.6464982   13.0125265   16.845333  ]
 ...
 [ 22.239254     9.072902    21.035189  ]
 [ 21.519667     5.219161   -10.131542  ]
 [ 26.423035    22.283928    22.010372  ]]
[[ 24.6095     -8.180533  -16.283346 ]
 [  0.5920953  32.175915   30.18335  ]
 [-11.354603    4.047818   15.81571  ]
 ...
 [ 21.645716   11.2934885  18.256294 ]
 [ 25.235325    3.5653467  -9.864834 ]
 [-11.892142    0.7655274  25.913414 ]]
[[  0.8683733 -11.264513   25.905312 ]
 [  4.0392585  30.770752  -10.051561 ]
 [ 28.499834   -7.6057253  16.489109 ]
 ...
 [ 16.585363    8.436509   23.60794  ]
 [ 26.432419    8.154136  -13.183158 ]
 [-16.907312    8.793828   32.5297   ]]
[[  

Centering molecules: 90it [00:03, 24.67it/s]

[[  1.1911817 -11.917258   25.220657 ]
 [  6.0411344  -2.699458   -4.5219846]
 [-13.417344   29.133472   23.490824 ]
 ...
 [ 13.95967     5.100066   18.367249 ]
 [ 30.341434   12.880885  -15.666772 ]
 [ -7.7711596  18.381166   27.579031 ]]
[[  4.6699357  -7.321247   26.182364 ]
 [  3.5799983   0.7478062  -3.6853552]
 [-10.60843    27.160131   24.010826 ]
 ...
 [  9.174139    6.201461   19.69146  ]
 [ 28.51415    12.247079   30.577158 ]
 [ -8.6287     20.928318   21.55646  ]]
[[  6.389335    -6.2397995   22.227169  ]
 [  1.0124949    0.85884774  -0.31817088]
 [-10.540085    31.240835    21.105753  ]
 ...
 [  9.244573     6.9007974   20.269678  ]
 [-16.75897     11.473741   -16.1352    ]
 [ -9.418357    21.2839      21.423532  ]]
[[  6.2034717   8.146623   22.66216  ]
 [ 10.94488   -14.838482   -1.0878954]
 [-16.001686  -11.034853   11.089435 ]
 ...
 [ 16.988691    3.235728   27.741472 ]
 [ 24.811628   18.778057   -2.3068585]
 [-11.439855   29.464024  -14.8081   ]]
[[ -0.92316663   0.147

Centering molecules: 96it [00:03, 24.72it/s]

[[  2.3714695   3.8680654  11.191629 ]
 [  6.8658133  -3.9140055   2.3083036]
 [-11.634791  -11.06657    14.930677 ]
 ...
 [ 15.050258    9.612604   26.388105 ]
 [ 26.70434    25.013796  -12.03075  ]
 [ -8.337117  -11.3652525  -8.027388 ]]
[[ -8.939514   -9.053537    8.326471 ]
 [ 10.195725   -5.1414723  10.743765 ]
 [ 28.12444   -14.644952    6.0844984]
 ...
 [ 15.053873   10.137476   28.071901 ]
 [ 32.329815   14.387046  -15.556788 ]
 [ 24.592827    1.5307083 -11.0822525]]
[[ -8.500388   -9.4318905  -1.2104329]
 [ 20.171434   -3.9540985  10.804743 ]
 [ 31.040741  -14.219933   14.724416 ]
 ...
 [ 14.065886   11.525822   23.503288 ]
 [-14.078697   16.335855   -3.5551035]
 [ 22.53706     4.123038  -12.657297 ]]
[[ -8.045911    -7.265065     0.74124545]
 [ 22.00921     -2.193993     0.4933277 ]
 [ 29.586893   -14.232555     9.542198  ]
 ...
 [  6.2450995   -1.0230048   20.85069   ]
 [ 28.776197     9.280499    31.246151  ]
 [ 21.72186      1.4786444   22.816816  ]]
[[ -1.5385249    0.777

Centering molecules: 100it [00:04, 24.63it/s]

[[-11.773169   -1.4057083  -8.838608 ]
 [ 11.581485   20.306868    5.2281647]
 [ 23.51309   -13.436639    7.323205 ]
 ...
 [-11.774336    5.2438283  -9.044884 ]
 [ 11.008248    0.3412093  -0.4235097]
 [  7.998496    1.2183301  26.767746 ]]
[[-12.631078    2.0857346  -7.230706 ]
 [ 17.081472   18.0634     12.525729 ]
 [ 21.819313  -10.875286   10.861496 ]
 ...
 [-12.826255   -7.687822   -8.654946 ]
 [  3.056195    0.8592632   3.474479 ]
 [ 13.715702    0.7083097  31.108541 ]]
[[ 26.56783    -6.4176483  27.947918 ]
 [ -7.9795184  23.080048    9.787119 ]
 [ 17.483189   28.518686   17.222666 ]
 ...
 [-12.997636   -5.392756   -9.878015 ]
 [ 12.143205   -9.805565   -1.6667237]
 [  7.021599  -14.922069  -10.787454 ]]
